### ISSUE TITLE
Create route for getting player stats

### ISSUE THREAD

**Issue by apangasa** [apangasa/cen3031-skjsports#50]

**Comment by sumeetjena01** [comment]
Stats:

- GKs (GK) - Nation, matches played, total clean sheets, save percentage
- Defenders (DF) - Nation, matches played, tackles per 90, interceptions per 90, tackle percentage
- Midfielders (MF) - Nation, matches played, goals, assists, pass completion percentage, xA per 90, tackles per 90, interceptions per 90
- Forwards (FW) - Nation, matches played, goals, assists, xG per 90, xA per 90
